#!/bin/sh

wmname LG3D &
vmware-user-suid-wrapper &

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-fill /home/parrot/Desktop/Wallpaper/3.jpg &
bspc monitor -d I II III IV V VI VII VIII IX X XI

xrandr --output Virtual --mode 1920x1080

bspc config border_width         1
bspc config focused_border_color "#252627"
bspc config normal_border_color "#252627"
bspc config window_gap           12
bspc config split_ratio          0
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# picom
bspc --lxappearance Kripton &

autostart
