#!/bin/sh

wmname LG3D &
vmware-user-suid-wrapper &

pgrep -x sxhkd > /dev/null || sxhkd &

feh --bg-fill /home/parrot/Desktop/Wallpaper/1.jpg &
bspc monitor -d I II III IV V VI VII VIII IX X XI

xrandr --output Virtual --mode 1920x1080

bspc config border_width         2
bspc config focused_border_color "#C53A52"
bspc config normal_border_color "#C53A52"
bspc config window_gap           12
bspc config split_ratio          0
bspc config borderless_monocle   false
bspc config gapless_monocle      false

#bspc rule -a Gimp desktop='^8' state=floating follow=off
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

# POLYBAR
# ~/.config/polybar/launch.sh

# CUSTOM
# bspc config focus_follows_pointer true

# PICOM
picom
bspc --lxappearance Kripton &

autostart
